### ISSUE TITLE
Box.Eval Parameters

### ISSUE THREAD

**Issue by meraghi** [progaudi/progaudi.tarantool#132]
How a parameter will be defined in Box.Eval<> expression?

**Comment by aensidhe** [comment]
Will [this](https://tarantool.io/en/doc/1.7/reference/reference_lua/net_box.html#net-box-eval) help?

**Comment by meraghi** [comment]
Not really, I meant in .net client

**Comment by aensidhe** [comment]
Nothing specific: https://github.com/progaudi/progaudi.tarantool/blob/master/tests/progaudi.tarantool.tests/Box/Eval_Should.cs#L18

**Comment by meraghi** [comment]
Assuming this:

var result = _box.Eval<InputType, string>(
                        @"
                                box.begin()

                                someFunction(1, 'test', {{ input }})
                                someOtherFunction()

                                box.commit()

                                ", input);

How the input parameter can be referenced in the expression?

**Comment by meraghi** [comment]
And in this test:

[Fact]
        public async Task evaluate_expression()
        {
            using (var tarantoolClient = await Client.Box.Connect(ConnectionStringFactory.GetReplicationSource_1_7()))
            {
                var result = await tarantoolClient.Eval<TarantoolTuple<int, int, int>, int>("return ...", TarantoolTuple.Create(1, 2, 3));

                result.Data.ShouldBe(new[] {1, 2, 3});
            }
}

the result has to be int not TarantoolTuple. at least in my version.
