### ISSUE TITLE
Box.Eval serialize Bin8 property as a Str8 property

### ISSUE THREAD

**Issue by meraghi** [progaudi/progaudi.tarantool#135]
using this code to insert a user object with a byte[] property:

Box.Eval<TarantoolTuple<User>, string>("box.space.user:insert( ... )", TarantoolTuple.Create(user));

returns "Got Str8 (0xD9), while expecting one of these: Bin8, Bin16, Bin32, Null" when we select the object.
while calling a simple insert:

Space.Insert(user)

is OK when the object is selected.

Selecting with space.select or box.eval returns same result.

**Comment by aensidhe** [comment]
Which version of Tarantool do you use?

**Comment by meraghi** [comment]
1.9.1-16-ge9bf00f

**Comment by aensidhe** [comment]
Resolved in #139
