### ISSUE TITLE
Wrong IPROTO_SQL_INFO and SQL_INFO_ROW_COUNT codes

### ISSUE THREAD

**Issue by ilnardinio** [progaudi/progaudi.tarantool#148]
In tarantool [documentation 2.3](https://www.tarantool.io/ru/doc/2.3/dev_guide/internals/box_protocol/#binary-protocol-responses-for-sql) is given different IPROTO_SQL_INFO(0x42) and SQL_INFO_ROW_COUNT(0x00) codes ([Codes file](https://github.com/progaudi/progaudi.tarantool/blob/master/src/progaudi.tarantool/Model/Enums/Key.cs) SqlInfo and SqlRowCount fields). May be something changed in protocol in new version of tarantool.

**Comment by Totktonada** [comment]
See https://github.com/tarantool/doc/issues/467

**Comment by ilnardinio** [comment]
Thanks
