### ISSUE TITLE
Error message "Space with name 'Dummy' was found!"

### ISSUE THREAD

**Issue by pelhu** [progaudi/progaudi.tarantool#98]
Hi,
For inexistant space i recieve "Space with name 'Dummy' was found!" error when i try insert tuple.

**Comment by aensidhe** [comment]
Hi.

What do you expect?

**Comment by pelhu** [comment]
Hi,
"Space with name 'Dummy' was **NOT** found!"

**Comment by aensidhe** [comment]
Oh, thank you very much. Sorry, I didn't pay attention.

**Comment by pelhu** [comment]
You welcome :)
Thanks for this project.

**Comment by roman-kozachenko** [comment]
Hello,
We fixed that typo.
You can find that fix in https://www.nuget.org/packages/Tarantool.CSharp/0.6.1
PS: we renamed project, next package updates will be here https://www.nuget.org/packages/progaudi.tarantool/
